### ISSUE TITLE
caption not defined in German Language

### ISSUE THREAD

**Issue by pthoelken** [marcopiovanello/yt-dlp-web-ui#235]
**Version running**
:latest Tag

**Describe the bug**
`caption not defined` in some german translation instead of correct translations in https://github.com/marcopiovanello/yt-dlp-web-ui/blob/master/frontend/src/assets/i18n.yaml

**Screenshots**
![image](https://github.com/user-attachments/assets/3adebc8b-8ee2-459d-b2e0-268288678fd7)

**Comment by marcopiovanello** [comment]
```yaml
  rpcPollingTimeTitle: RPC polling time
  rpcPollingTimeDescription: A lower interval results in higher CPU usage (server and client side)
  urlBase: URL base, for reverse proxy support (subdir), defaults to empty
```

this keys were missing and need a translation :)
