### ISSUE TITLE
Error while conencting to RPC server (Apache)

### ISSUE THREAD

**Issue by Molenfeuer** [marcopiovanello/yt-dlp-web-ui#247]
I know this issue was already opened by others, but in my case its may related to misconfiguration of my server.. I use Apache2 instead of NGINX as reverse-proxy for my instance in version `RPC v3.2.3 / yt-dlp v2025.01.15`. Also the webserver is only accessible by using an https connection.

When I open the website of my yt-dlp-web-ui docker I get these errors at the same time:

```
Error while conencting to RPC server ("yt-dlp.domain.de"/""/)
Error while conencting to RPC server (yt-dlp.domain.de)
```

My (Apache) Proxy config is like:

```
[...]
ProxyPreserveHost on
ProxyPass "/"  "http://localhost:3033/"
ProxyPassReverse "/"  "http://localhost:3033/"

<Proxy *>
  Authtype Basic
  Authname "Password Required"
  AuthUserFile XXX
  Require valid-user
</Proxy>
[...]
```

And finally my compose file
```
services:
  yt-dlp-webui:
    image: marcobaobao/yt-dlp-webui
    ports:
      - 3033:3033
    volumes:
      - yt-dlp-web-ui:/downloads
    healthcheck:
      test: curl -f http://localhost:3033 || exit 1
    restart: unless-stopped

volumes:
  yt-dlp-web-ui:
```
