### ISSUE TITLE
cannot unmarshal !!str `-x` into config.Config

### ISSUE THREAD

**Issue by magnulu** [marcopiovanello/yt-dlp-web-ui#272]
**Version running**
UI v3.2.5
RPC v3.2.5
yt-dlp v2025.02.19 

docker image: marcobaobao/yt-dlp-webui:latest 
Docker Compose version v2.32.4

docker-compose.yml:
```
services:
  yt-dlp-webui:
    container_name: yt-dlp-webui
    image: marcobaobao/yt-dlp-webui:latest
    ports:
      - 3033:3033
    volumes:
      - config:/config
    healthcheck:
      test: curl -f http://localhost:3033 || exit 1
    restart: unless-stopped
```

**Describe the bug**
Starting up, I get the following error:
```
$ docker compose up
[+] Running 1/1
 ✔ Container yt-dlp-webui  Recreated                                                                                                                                                                                                     0.1s 
Attaching to yt-dlp-webui
yt-dlp-webui  | 2025/02/27 15:37:00  config  yaml: unmarshal errors:
yt-dlp-webui  |   line 4: cannot unmarshal !!str `-x` into config.Config
yt-dlp-webui  | time=2025-02-27T15:37:00.312Z level=INFO msg="yt-dlp-webui started" address=0.0.0.0:3033
```

**To Reproduce**
1. Create config/config.yml with the following content
```
# Lines starting with # are comments

# Always extract audio
-x
```
2. Making sure the encoding is correct:
```
$ file config.yml 
config.yml: Unicode text, UTF-8 (with BOM) text
```
3. Starting the service with `docker compose up`

**Expected behavior**
No error and config being read.

**Additional context**
The config is actually located in different directories, but I am sure the correct config file is being read.
