### ISSUE TITLE
How to use arguments with yt-dlp when also using web-ui (browser impersonation issue)

### ISSUE THREAD

**Issue by Kribensisis** [marcopiovanello/yt-dlp-web-ui#279]
**Describe the bug**
I see in the logs that I'm triggering Cloudflare anti-bot protection when downloading from some sites and need to install a yt-dlp dependency to work around this:

```time=2025-03-15T23:52:43.792Z level=ERROR msg="yt-dlp process error" id=d79590ad url="https://www.website.com/download" err="ERROR: [generic] Got HTTP Error 403 caused by Cloudflare anti-bot challenge; see https://github.com/yt-dlp/yt-dlp#impersonation for how to install the required impersonation dependency, and try again with --extractor-args \"generic:impersonate\""```

Those steps want me to install `curl_cffi` and then run yt-dlp with some arguments, but I don't know how to do that *with web-ui*, since I run it in Docker. In my docker compose, there's no external version of yt-dlp defined, it just works and stays updated—presumably getting updated by web-ui when there's a new version. 

**Question** 

How can I keep using yt-dlp web-ui and also use these arguments with yt-dlp? It's a little beyond me. Do I need to stop using the default docker compose and instead define an external version of yt-dlp in my docker compose?

**Comment by Kribensisis** [comment]
@marcopiovanello maybe you would know? I installed `curl_cffi` and `yt-dlp` locally and tried pointing web-ui to that, but the docker compose I used was a complete guess. A file that didn't trigger the anti-bot stuff did download, but one that did trigger it still failed with the same error. 

That makes me think web-ui ignored my external yt-dlp completely. I'll paste it here, it's certain to be wrong. 

```
services:
  yt-dlp-webui:
    image: marcobaobao/yt-dlp-webui
    container_name: dlp-ui
    ports:
      - 3033:3033
    volumes:
      - /path/to/downloads:/downloads
      - /path/to/yt-dlp:/usr/local/bin/yt-dlp # Use external yt-dlp
    restart: unless-stopped
    command:
      - yt-dlp-webui
      - --out
      - /downloads
      - --driver
      - /usr/local/bin/yt-dlp
      - --extractor-args
      - generic:impersonate
  ```

What should I really be doing to get this to work when running web-ui in Docker?

**Comment by marcopiovanello** [comment]
![Image](https://github.com/user-attachments/assets/49581dcd-3727-49c6-b47e-0e6a8b74bc49)

![Image](https://github.com/user-attachments/assets/ff52c444-651e-43d9-85a6-42ca5f867768)

**Comment by btbristow** [comment]
@marcopiovanello what am I missing here? That was the first thing I tried and custom arguments don't appear. I don't have the text box you're showing. 

<img width="1515" alt="Image" src="https://github.com/user-attachments/assets/55a0866d-14ac-4a2d-ad1e-ace4198aa41e" />

Do I need something in my compose? This is what I'm running without trying to call an external version of yt-dlp:

```
services:
  yt-dlp-webui:
    image: marcobaobao/yt-dlp-webui
    container_name: dlp-ui
    ports:
      - 3033:3033
    volumes:
      - /path/to/downloads:/downloads
    restart: unless-stopped
```

**Comment by btbristow** [comment]
@marcopiovanello what am I missing here? That was the first thing I tried and custom arguments don't appear. I don't have the text box you're showing. 

<img width="1515" alt="Image" src="https://github.com/user-attachments/assets/55a0866d-14ac-4a2d-ad1e-ace4198aa41e" />

Do I need something in my compose? This is what I'm running without trying to call an external version of yt-dlp:

```
services:
  yt-dlp-webui:
    image: marcobaobao/yt-dlp-webui
    container_name: dlp-ui
    ports:
      - 3033:3033
    volumes:
      - /path/to/downloads:/downloads
    restart: unless-stopped
```

**Comment by Kribensisis** [comment]
@marcopiovanello what am I missing here? That was the first thing I tried and custom arguments don't appear. I don't have the text box you're showing. 

<img width="1515" alt="Image" src="https://github.com/user-attachments/assets/55a0866d-14ac-4a2d-ad1e-ace4198aa41e" />

Do I need something in my compose? This is what I'm running without trying to call an external version of yt-dlp:

```
services:
  yt-dlp-webui:
    image: marcobaobao/yt-dlp-webui
    container_name: dlp-ui
    ports:
      - 3033:3033
    volumes:
      - /path/to/downloads:/downloads
    restart: unless-stopped
```
