### ISSUE TITLE
Language Request: Add Vietnamese (vi) Language Translation

### ISSUE THREAD

**Issue by kogakisaki** [marcopiovanello/yt-dlp-web-ui#310]
Hi maintainers,

I've noticed that the application doesn't currently support Vietnamese. To help make it more accessible to Vietnamese-speaking users, I have translated the language strings found in the primary language file into Vietnamese.

Here is the proposed content for a `vi.yml` language file:
```yml
keys:
  urlInput: URL Video (mỗi dòng một URL)
  statusTitle: Trạng thái
  statusReady: Sẵn sàng
  selectFormatButton: Chọn định dạng
  startButton: Bắt đầu
  abortAllButton: Hủy tất cả
  updateBinButton: Cập nhật tệp nhị phân yt-dlp
  darkThemeButton: Giao diện tối
  lightThemeButton: Giao diện sáng
  settingsAnchor: Cài đặt
  serverAddressTitle: Địa chỉ máy chủ
  serverPortTitle: Cổng
  extractAudioCheckbox: Trích xuất âm thanh
  noMTimeCheckbox: Không đặt thời gian sửa đổi tệp
  bgReminder: Khi bạn đóng trang này, quá trình tải xuống sẽ tiếp tục trong nền.
  toastConnected: 'Đã kết nối tới '
  toastUpdated: Đã cập nhật tệp nhị phân yt-dlp!
  formatSelectionEnabler: Bật lựa chọn định dạng video/âm thanh
  themeSelect: 'Giao diện'
  languageSelect: 'Ngôn ngữ'
  overridesAnchor: Ghi đè
  pathOverrideOption: Bật ghi đè đường dẫn đầu ra
  filenameOverrideOption: Bật ghi đè tên tệp đầu ra
  autoFileExtensionOption: Tự động thêm phần mở rộng tệp
  customFilename: Tên tệp tùy chỉnh (để trống để dùng mặc định)
  customPath: Đường dẫn tùy chỉnh
  customArgs: Bật đối số yt-dlp tùy chỉnh (quyền lực lớn = trách nhiệm lớn)
  customArgsInput: Đối số yt-dlp tùy chỉnh
  rpcConnErr: Lỗi khi kết nối tới máy chủ RPC
  splashText: Không có bản tải xuống nào đang hoạt động
  archiveTitle: Lưu trữ
  clipboardAction: Đã sao chép URL vào bộ nhớ tạm
  playlistCheckbox: Tải xuống danh sách phát
  restartAppMessage: Cần tải lại trang để áp dụng thay đổi
  servedFromReverseProxyCheckbox: Đang hoạt động sau một reverse proxy
  urlBase: URL gốc, để hỗ trợ reverse proxy (thư mục con), mặc định là trống
  newDownloadButton: Tải xuống mới
  homeButtonLabel: Trang chủ
  archiveButtonLabel: Lưu trữ
  settingsButtonLabel: Cài đặt
  rpcAuthenticationLabel: Xác thực RPC
  themeTogglerLabel: Chuyển đổi giao diện
  loadingLabel: Đang tải...
  appTitle: Tiêu đề ứng dụng
  savedTemplates: Mẫu đã lưu
  templatesEditor: Trình chỉnh sửa mẫu
  templatesEditorNameLabel: Tên mẫu
  templatesEditorContentLabel: Nội dung mẫu
  logsTitle: 'Nhật ký'
  awaitingLogs: 'Đang chờ nhật ký...'
  bulkDownload: 'Tải xuống tệp trong một kho lưu trữ zip'
  rpcPollingTimeTitle: Thời gian thăm dò RPC
  rpcPollingTimeDescription: Khoảng thời gian ngắn hơn dẫn đến việc sử dụng CPU cao hơn (phía máy chủ và máy khách)
  templatesReloadInfo: Để đăng ký một mẫu mới, có thể cần tải lại trang.
  livestreamURLInput: URL phát trực tiếp
  livestreamStatusWaiting: Đang chờ/Chờ bắt đầu
  livestreamStatusDownloading: Đang tải xuống
  livestreamStatusCompleted: Hoàn thành
  livestreamStatusErrored: Bị lỗi
  livestreamStatusUnknown: Không xác định
  livestreamNoMonitoring: Không có luồng trực tiếp nào được giám sát
  livestreamDownloadInfo: |
    Chức năng này sẽ giám sát luồng trực tiếp chưa bắt đầu. Mỗi quy trình sẽ được thực thi với --wait-for-video 10.
    Nếu cung cấp một luồng trực tiếp đã bắt đầu, nó vẫn sẽ được tải xuống nhưng tiến trình sẽ không được theo dõi.
    Sau khi bắt đầu, luồng trực tiếp sẽ được chuyển sang trang tải xuống.
  livestreamExperimentalWarning: Tính năng này vẫn đang trong giai đoạn thử nghiệm. Có thể xảy ra lỗi!
  accentSelect: 'Màu nhấn'
  generalDownloadSettings: 'Cài đặt Tải xuống Chung'
  deleteCookies: Xóa Cookies
  noFilesFound: 'Không tìm thấy tệp nào'
  tableView: 'Chế độ xem bảng'
  deleteSelected: 'Xóa mục đã chọn'
  subscriptionsButtonLabel: 'Đăng ký'
  subscriptionsEmptyLabel: 'Không có đăng ký nào'
  subscriptionsURLInput: 'URL Kênh'
  subscriptionsInfo: |
    Đăng ký một kênh được xác định. Chỉ video mới nhất sẽ được tải xuống.
    Công việc giám sát sẽ được lên lịch/kích hoạt bởi một biểu thức cron được xác định (mặc định là 5 phút một lần nếu để trống).
  cronExpressionLabel: 'Biểu thức Cron'
  editButtonLabel: 'Chỉnh sửa'
  newSubscriptionButton: Đăng ký mới
  clearCompletedButton: 'Xóa mục đã hoàn thành'
```
Please let me know if any changes are needed or if you would prefer this as a Pull Request.

Thank you for considering this contribution!
